### ISSUE TITLE
Doesn't seem to work – Not sure why?

### ISSUE THREAD

**Issue by akaalias** [Darakah/obsidian-paper-cut#1]
Hi there, just installed, activated and configured the plugin. Even reloaded Obsidian. 

My settings are this – the tag I specified is NOT editable but the placeholder text (?), same with the count.

<img width="906" alt="Screenshot 2021-02-09 at 15 07 53" src="https://user-images.githubusercontent.com/111555/107375215-c7160c80-6ae8-11eb-9cee-69b34b11f5a2.png">

Nothing happens in a sample note:

<img width="1109" alt="Screenshot 2021-02-09 at 15 08 17" src="https://user-images.githubusercontent.com/111555/107375402-ff1d4f80-6ae8-11eb-9fee-fe4932c85427.png">

**Comment by Darakah** [comment]
Hello, 

Can you show the YAML of that note please? 
The specified tag (in your case `mytag`) must be in the YAML not just a tag in the note, as the plugin will pull YAML tags (as shown in the readme)

<img width="253" alt="Screen Shot 2021-02-10 at 4 04 33 PM" src="https://user-images.githubusercontent.com/29651407/107528023-acf82f00-6bb9-11eb-8299-809c3a26b7ca.png">

`the tag I specified is NOT editable but the placeholder text (?), same with the count.` Can you clarify what this means?

**Comment by akaalias** [comment]
Got it! I had not seen that requirement. Since I don't use frontmatter/YAML ever, can you please make it to just use regular tags?

**Comment by Darakah** [comment]
Glad it worked. 

Will add it in the next release.
